name: todo_sprint
description: "Todo Sprint is a simple todo app that helps you to manage your daily tasks."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter

  # UI
  iconsax: ^0.0.8
  flutter_colorpicker: ^1.1.0
  responsive_framework: ^1.5.1

  # Routing
  go_router: ^14.2.7

  # State Management
  provider: ^6.1.2

  # Local Storage
  shared_preferences: ^2.3.2

  # Firebase
  firebase_core: ^3.4.0
  firebase_analytics: ^11.3.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.3.0

  # Other
  intl: ^0.19.0
  timezone: ^0.9.4
  flutter_local_notifications: ^17.2.2
  firebase_messaging: ^15.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^3.0.0
  
flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
