name: todo_sprint
description: "Todo Sprint is a simple todo app that helps you to manage your daily tasks."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter

  # UI
  iconsax: ^0.0.8
  responsive_framework: ^1.5.1

  # Routing
  go_router: ^14.2.7

  # State Management
  provider: ^6.1.2

  # Local Storage
  shared_preferences: ^2.3.2

  # Firebase
  firebase_core: ^3.4.0
  firebase_analytics: ^11.3.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.3.0

  # Other
  intl: ^0.19.0
  timezone: ^0.9.4
  flutter_local_notifications: ^17.2.2
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  integration_test:
    sdk: flutter
    
  flutter_lints: ^3.0.0
  
flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/icons/AppIcons.ttf

    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300
          style: normal

        - asset: assets/fonts/Lato-Regular.ttf
          weight: 400
          style: normal

        - asset: assets/fonts/Lato-Medium.ttf
          weight: 500
          style: normal

        - asset: assets/fonts/Lato-Semibold.ttf
          weight: 600
          style: normal

        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
          style: normal